CREATE TABLE CONFIG (
	CONFIGID NUMERIC(20) NOT NULL,
	NOME VARCHAR(300),
	ENDERECO VARCHAR(100),
	CONTATO VARCHAR(20),
	CONTADOR VARCHAR(100),
	LOGOTIPO TEXT,
	CONSTRAINT PK_CONFIG PRIMARY KEY (CONFIGID)
);

INSERT INTO CONFIG (CONFIGID, NOME) VALUES ('1', 'ProcessADV');